### PR TITLE
feat: json schema for version 0.2.0

### PR DESCRIPTION
**Pull request by StefanFl**
JSON Schema is a great way to check if an OpenVEX document is compliant with the specification.

This is still a draft pull request, because:
* The maintainers of the OpenVEX specification need to decide if this is a helpful contribution.
* The JSON Schema worked with my OpenVEX documents, but I would like to see more testing by the OpenVEX maintainers.
* If the JSON Schema will be accepted, it shall be mentioned in the README.md file.

Closes https://github.com/openvex/spec/issues/14

### CODE REVIEW

**Comment by sschuberth** [comment]
> * The maintainers of the OpenVEX specification need to decide if this is a helpful contribution.

IMO it clearly is, as it also help to auto-generate code to write out VEX documents in different programming languages.

**Comment by puerco** [comment]
Hey @StefanFl thanks a lot for this contribution it is of course super valuable! The JSON schema is something we've been meaning to write for a while now. Let me take a look at it and I'll add some early comments.

**Comment by StefanFl** [comment]
I have changed some formats to  from `uri`to `iri`, which is closer to the specification.

**Comment by StefanFl** [comment]
@sschuberth , @puerco There is one thing in the specification I don't understand: According to https://github.com/openvex/spec/blob/main/OPENVEX-SPEC.md#component-fields the fields `@id`, `identifiers` and `hashes` are all optional. Could I create a (sub)component without any of these? That would be an empty `product`. Or should it have a conditional requirement?

**Comment by sschuberth** [comment]
> Or should it have a conditional requirement?

Just guessing, I believe you must have at least on of these, as either single one should be enough to uniquely identify a component.

**Comment by StefanFl** [comment]
> > Or should it have a conditional requirement?
> 
> Just guessing, I believe you must have at least on of these, as either single one should be enough to uniquely identify a component.

At least one of `@id` or `identifiers` would make sense to have. Just the `hashes` might not be enough. 

I can implement this in the JSON Schema, but this would be more strict than the specification.

> > > Or should it have a conditional requirement?
> > 
> > 
> > Just guessing, I believe you must have at least on of these, as either single one should be enough to uniquely identify a component.
> 
> At least one of `@id` or `identifiers` would make sense to have. Just the `hashes` might not be enough.
> 
> I can implement this in the JSON Schema, but this would be more strict than the specification.

Now at least one of `@id` or `identifiers` is required for (sub)components.

**Comment by StefanFl** [comment]
I have made a small fix. From "either a machine readable `justification` label or a free form text `impact_statement`" I thought these two attributes are mutually exclusive. But the example shows, that both are allowed together.

**Comment by StefanFl** [comment]
And I have included a reference to the JSON Schema in the README. From my point of view the PR is ready to be merged after your review.

**Comment by StefanFl** [comment]
Hi guys, anything you need from me to get the pull request accepted?

**Comment by puerco** [comment]
Wow @StefanFl sorry, I totally lost track of the PR and forgot to review it :(

This is awesome, thank you so much for working on this, the schema will let us unlock a bunch of new cases where we need to validate the documents, CI tests and more. Thank you, thank you.

For posterity's sake, here is a screenshot of your schema validating the cilium openvex file, which is quite large :sunglasses: 

image

**Review by puerco — APPROVED** [review]

**Pull request merged**
